# Generated by Django 4.2.2 on 2023-06-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(default='ok', max_length=250),
            preserve_default=False,
        ),
    ]
